name: MoneySLand
main: money.MoneySLand

load: STARTUP
author: Him188
version: "1.1.0"
api: ["1.0.0"]

depend:
- Money

description: "地皮"

# TODO 2017/07/03 支持配置文件修改权限
permissions:
  money.permission.sland:
    default: op
    description: "Allows op to do something about MoneySLand"
    children:
      money.permission.sland.modify:
        default: op
        description: "Allows op to modify the land though he wasn't invited from the land"
        children:
          money.permission.sland.modify.place:
            default: op
            description: "Allows op to place blocks on the land through he wasn't invited from the land"
          money.permission.sland.modify.break:
            default: op
            description: "Allows op to break blocks on the land through he wasn't invited from the land"
          money.permission.sland.modify.interact:
            default: op
            description: "Allows op to interact blocks on the land through he wasn't invited from the land"
      money.permission.sland.buy:
        default: true
        description: "Allows everyone to buy the land"
  money.command.sland:
    default: op
    descriptin: "Allows players to run MoneySLand command"
    children:
      money.command.sland.generateland:
        default: op
        description: "Allows op to run GenerateLand command"
      money.command.sland.gotoland:
        default: true
        description: "Allows players to run GotoLand command"
      money.command.sland.idleland:
        default: true
        description: "Allows players to run IdleLand command"
      money.command.sland.landid:
        default: true
        description: "Allows players to run LandId command"
      money.command.sland.sellland:
        default: true
        description: "Allows players to run SellLand command"
        children:
           money.command.sland.sellland.others:
             default: op
             description: "Allows op to run SellLandOthers command"
      money.command.sland.clearland:
        default: true
        description: "Allows players to run ClearLand command"
        children:
           money.command.sland.clearland.others:
             default: op
             description: "Allows op to run ClearLandOthers command"
      money.command.sland.myland:
        default: true
        description: "Allows players to run MyLandCommand command"
        children:
           money.command.sland.myland.others:
             default: op
             description: "Allows op to run MyLandOthers command"
      money.command.sland.landinvitee:
        default: op
        description: "Allows players to run LandInvitee command"
        children:
           money.command.sland.landinvitee.add:
             default: true
             description: "Allows op to run LandInviteeAdd command"
             children:
                money.command.sland.landinvitee.add.others:
                  default: op
                  description: "Allows op to run LandInviteeAddOthers command"
           money.command.sland.landinvitee.remove:
             default: true
             description: "Allows op to run LandInviteeRemove command"
             children:
                money.command.sland.landinvitee.remove.others:
                  default: op
                  description: "Allows op to run LandInviteeRemoveOthers command"
           money.command.sland.landinvitee.list:
             default: true
             description: "Allows op to run LandInviteeList command"
             children:
                money.command.sland.landinvitee.list.others:
                  default: op
                  description: "Allows op to run LandInviteeListOthers command"