name: MoneySLand
main: money.MoneySLand

load: POSTWORLD
author: Him188
version: "1.0.0"
api: ["1.0.0"]

depend:
- Money

description: "地皮"


permissions:
  # 允许服务器管理员直接修改地皮 (尽管他不是地皮的主人或邀请者)
  # Allows op to modify the land through he wasn't invited from the land
  money.sland.permission.modify:
    default: op
    description: "Allows op to modify the land though he wasn't invited from the land"

  # 允许所有玩家购买地皮
  # Allows everyone to buy the land
  money.sland.permission.buy:
    default: true
    description: "Allows everyone to buy the land"

  # 允许服务器管理员使用木棒使地皮变为公益地皮 (任何玩家都可以直接修改地皮)
  # Allows op to make the land public (Everyone can modify the land)
  money.sland.permission.free:
     default: op
     description: "Allows op to make the land public (Everyone can modify the land)"